export const ON_TEXT_CHANGE_EMAIL = '@signUp/ON_TEXT_CHANGE_EMAIL';
export const ON_TEXT_CHANGE_PASSWORD = '@signUp/ON_TEXT_CHANGE_PASSWORD';
export const ON_TEXT_CHANGE_FULL_NAME = '@signUp/ON_TEXT_CHANGE_FULL_NAME';
export const ON_TEXT_CHANGE_PHONE_NUMBER =
  '@signUp/ON_TEXT_CHANGE_PHONE_NUMBER';
export const ON_CHANGE_AVATAR = '@signUp/ON_CHANGE_AVATAR';

export const SIGN_UP = '@signUp/SIGN_UP';
export const SIGN_UP_SUCCESSFULLY = '@signUp/SIGN_UP_SUCCESSFULLY';
export const SIGN_UP_FAILURE = '@signUp/SIGN_UP_FAILURE';
