export const SIGN_IN = '@signIn/SIGN_IN';
export const SIGN_IN_SUCCESSFULLY = '@signIn/SIGN_IN_SUCCESSFULLY';
export const SIGN_IN_FAILURE = '@signIn/SIGN_IN_FAILURE';

export const ON_CHANGE_SIGN_IN_METHOD = '@signIn/ON_CHANGE_SIGN_IN_METHOD';

export const ON_TEXT_CHANGE_EMAIL = '@signIn/ON_TEXT_CHANGE_EMAIL';
export const ON_TEXT_CHANGE_PASSWORD = '@signIn/ON_TEXT_CHANGE_PASSWORD';
export const ON_TEXT_CHANGE_PHONE_NUMBER =
  '@signIn/ON_TEXT_CHANGE_PHONE_NUMBER';
export const ON_TEXT_CHANGE_OTP_CODE = '@signIn/ON_TEXT_CHANGE_OTP_CODE';
